manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: divsmith
      url-base: https://github.com/divsmith
  projects:
    - name: zmk
      remote: divsmith
      revision: rp2040_zero
      import: app/west.yml
  self:
    path: config
